Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'lib/tasks/orchestration.rake'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/dummy/**/*'
