default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: ''
  port: 5432
  <% if ENV.key?('TEST_DATABASE_URL') %>
  url: <%= ENV['TEST_DATABASE_URL'] %>
  <% end %>

test:
  <<: *default
  host: localhost
  database: development_db
